CREATE DATABASE IF NOT EXISTS `surveys_db` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `surveys_db`;

DROP TABLE IF EXISTS `completed_answers`;
DROP TABLE IF EXISTS `questions`;
DROP TABLE IF EXISTS `survey_results`;
DROP TABLE IF EXISTS `surveys`;

CREATE TABLE `surveys` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `DESCR` varchar(255) DEFAULT NULL,
  `CRTTIME` datetime DEFAULT NULL,
  `CRTUSER` varchar(255) DEFAULT NULL,
  `UPDTIME` datetime DEFAULT NULL,
  `UPDUSER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `questions` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TXT` varchar(255) DEFAULT NULL,
  `ANS` varchar(255) DEFAULT NULL,
  `QTYPE` varchar(255) DEFAULT NULL,
  `CRTTIME` datetime DEFAULT NULL,
  `CRTUSER` varchar(255) DEFAULT NULL,
  `UPDTIME` datetime DEFAULT NULL,
  `UPDUSER` varchar(255) DEFAULT NULL,
  `SURVEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `SURVEY` FOREIGN KEY (`SURVEY`) REFERENCES `surveys` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `survey_results` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRTTIME` datetime DEFAULT NULL,
  `CRTUSER` varchar(255) DEFAULT NULL,
  `UPDTIME` datetime DEFAULT NULL,
  `UPDUSER` varchar(255) DEFAULT NULL,
  `SURVEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `RESULT_SURVEY` FOREIGN KEY (`SURVEY`) REFERENCES `surveys` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `completed_answers` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TXT` varchar(255) DEFAULT NULL,
  `CRTTIME` datetime DEFAULT NULL,
  `CRTUSER` varchar(255) DEFAULT NULL,
  `UPDTIME` datetime DEFAULT NULL,
  `UPDUSER` varchar(255) DEFAULT NULL,
  `QSTID` bigint(20) DEFAULT NULL,
  `SURVEY_RESULT` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ANSWER_QUESTION` FOREIGN KEY (`QSTID`) REFERENCES `questions` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ANSWER_RESULT` FOREIGN KEY (`SURVEY_RESULT`) REFERENCES `survey_results` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
