CREATE DATABASE IF NOT EXISTS `surveys_db` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `surveys_db`;

DROP TABLE  IF EXISTS `answers`;
DROP TABLE IF EXISTS `questions`;

CREATE TABLE `questions` (
    `QSTID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `QSTCRTTIME` DATETIME DEFAULT NULL,
    `QSTCRTUSR` VARCHAR(255) DEFAULT NULL,
    `QSTTEXT` VARCHAR(255) DEFAULT NULL,
    `QSTUPDTIME` DATETIME DEFAULT NULL,
    `QSTUPDUSR` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`QSTID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE `answers` (
    `ANSID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ANSCRTTIME` DATETIME DEFAULT NULL,
    `ANSCRTUSR` VARCHAR(255) DEFAULT NULL,
    `ANSTEXT` VARCHAR(255) DEFAULT NULL,
    `ANSUPDTIME` DATETIME DEFAULT NULL,
    `ANSUPDUSR` VARCHAR(255) DEFAULT NULL,
    `ANSQST` BIGINT(20) DEFAULT NULL,
    PRIMARY KEY (`ANSID`),
    KEY `FK_qkbr807m4h084yvsvayvtd3ld` (`ANSQST`),
    CONSTRAINT `FK_qkbr807m4h084yvsvayvtd3ld` FOREIGN KEY (`ANSQST`)
        REFERENCES `questions` (`QSTID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;

